### ISSUE TITLE
index.html doesn't work for me

### ISSUE THREAD

**Issue by ShreyasKashyap357** [Alwinator/aw-watcher-utilization#15]
For some reason, the index.html file does not work. It keeps showing network error. Maybe one of the modules is unable to connect to the internet or something. My internet connectivity is definitely not the problem because I can watch videos, download movies, use the ActivityWatch app without any hindrances. The index.html file by itself doesn't work, and on opening the visualization, the following is the exact error message: "Static content: index.html of watcher: aw-watcher-utilization not found!"

Also, I don't have any experience with such relatively complex code, and you could call me an amateur. I believe that in step 5 of the installation procedure, there should be a '#' on the line following [aw-qt], and the same should be in the first step of setting up the visulaization, on the line following [server.custom_static]. Before putting the symbols, it would show the error 400 - something like error with status 400, I don't exactly recall correctly.

**Comment by Alwinator** [comment]
@ShreyasKashyap357 I am not sure what you mean by the missing `#`. Adding a `#` in the YAML file means that the line is commented out and will not be used. Maybe this is also causing your error?

**Comment by ShreyasKashyap357** [comment]
If I didn't put the #, I was getting an error

**Comment by Alwinator** [comment]
Please provide more details and the contents of your config files. Also see https://github.com/Alwinator/aw-watcher-utilization/issues/9#issuecomment-1718668346

**Comment by ShreyasKashyap357** [comment]
This is the code that I see in the index.html file when I open it in the browser. Not sure if that is intended or not.
As of now, the path of the aw-watcher-visualization is:
C:\Users\<USER>\AppData\Local\activitywatch\activitywatch\aw-watcher-utilization\visualization
`<!DOCTYPE html>
<html lang="en"><head>
    <meta charset="UTF-8">
    <title>aw-watcher-utilization</title>
    <style>
        body{
            font-family: sans-serif;
            overflow: hidden;
            margin: 0;
            height: 100vh;
        }
    </style>
</head>
<body>Network Error</body></html>`

The code in aw-qt.toml is:
[aw-qt]
#autostart_modules = ["aw-server", "aw-watcher-afk", "aw-watcher-window", "aw-watcher-utilization"]

[aw-qt-testing]
#autostart_modules = ["aw-server", "aw-watcher-afk", "aw-watcher-window"]

The code in aw-server.toml is:
[server]
#host = "localhost"
#port = "5600"
#storage = "peewee"
#cors_origins = ""

[server.custom_static]
#aw-watcher-utilization = '''C:\Users\<USER>\AppData\Local\activitywatch\activitywatch\aw-watcher-utilization\visualization'''

[server-testing]
#host = "localhost"
#port = "5666"
#storage = "peewee"
#cors_origins = ""

[server-testing.custom_static]
I'll be trying the variations and commenting the response.

**Comment by Alwinator** [comment]
@ShreyasKashyap357 Remove the `#` before autostart_modules and before aw-watcher-utilization. They are wrong.

**Comment by MikeStirner** [comment]
You need to add a step or clarification to your install instructions, because I also needed to remove the # before autostart_modules in the aw-qt.toml file. It was there before I opened the file for the first time.

**Comment by Alwinator** [comment]
Fixed by https://github.com/Alwinator/aw-watcher-utilization/commit/4251b90d169d1d37535a0c5b5faa523518d8eb2a
