### ISSUE TITLE
Fix step 3 and 5 in installation instructions

### ISSUE THREAD

**Issue by MikeStirner** [Alwinator/aw-watcher-utilization#19]
Step 3 should say:
3. Move the folder to the directly ActivityWatch is installed (depends on your setup). For example, on Windows:
C:\Users\<USER>\AppData\Local\Programs\ActivityWatch\aw-watcher-utilization

But instead it says: 
Move the folder to the directly ActivityWatch is installed (depends on your setup). For example, on Windows: C:\Users\<USER>\AppData\Local\activitywatch\activitywatch\aw-watcher-utilization

Notice the lack of the "Programs" folder in the path, etc.

---

And for step 5 (change I made is bolded):
It should say: Add the aw-watcher-utilization to autostart_modules to enable auto-start **and remove the # if there is one**. It should look like this:
...

**Comment by Alwinator** [comment]
Thank you for your feedback! Done in https://github.com/Alwinator/aw-watcher-utilization/commit/4251b90d169d1d37535a0c5b5faa523518d8eb2a and https://github.com/Alwinator/aw-watcher-utilization/commit/524d802d1f78b69a7a7ae1f5deeedd1a3e88bc05?diff=unified&w=0
