### ISSUE TITLE
aw-watcher-utilization doesnt charge 

### ISSUE THREAD

**Issue by okapick** [Alwinator/aw-watcher-utilization#6]
Good morning. 

aw-watcher-utilization is not charge when i start AW. I did that you say in the readme. How could be aw-watcher-utilization added to the TIMELINE?

**Comment by Alwinator** [comment]
When aw-watcher-utilization is started and collects data, but you still see nothing or a wrong visualization in the timeline, it is most likely an Activity Watch issue. Please create a bug report [here](https://github.com/ActivityWatch/activitywatch/issues/new/choose).
