### ISSUE TITLE
Installation issue on Windows

### ISSUE THREAD

**Issue by afroze9** [Alwinator/aw-watcher-utilization#9]
The installation instructions need to be updated for windows.

Currently the instructions are to create a new folder called `aw-watcher-utilization` under `%localappdata%\activitywatch\activitywatch` and copy all contents there. However, the contents need to be copied to `%localappdata%\Programs\ActivityWatch\aw-watcher-utilization`.

Also, as mentioned in #7, we need to create an empty toml file called `aw-watcher-utilization.toml` under `%localappdata%\activitywatch\activitywatch\aw-watcher-utilization\`.

**Comment by ArthurusDent** [comment]
Thanks for the help!

Just something to add: My ActivityWatch has been installed for every user, so in this case the correct directory for the zip file content is C:\Program Files (x86)\ActivityWatch\aw-watcher-utilization.

When first modifying aw-qt.toml I did not realize that every line is commented out. You need to also remove the # in the first two lines of the file.

**Comment by Alwinator** [comment]
Fixed by https://github.com/Alwinator/aw-watcher-utilization/commit/e5f1935bedd1fd246aaf7d0d952e32d3f16ba54e

**Comment by sanbeichahegongheguo** [comment]
> Thanks for the help!
> 
> Just something to add: My ActivityWatch has been installed for every user, so in this case the correct directory for the zip file content is C:\Program Files (x86)\ActivityWatch\aw-watcher-utilization.
> 
> When first modifying aw-qt.toml I did not realize that every line is commented out. You need to also remove the # in the first two lines of the file.

If  I remove the #, it report bugs. So I still left $.

**Comment by ShreyasKashyap357** [comment]
> > Thanks for the help!
> > Just something to add: My ActivityWatch has been installed for every user, so in this case the correct directory for the zip file content is C:\Program Files (x86)\ActivityWatch\aw-watcher-utilization.
> > When first modifying aw-qt.toml I did not realize that every line is commented out. You need to also remove the # in the first two lines of the file.
> 
> If I remove the #, it report bugs. So I still left $.

Could you share the code that you implemented in the aw-qt.toml & aw-server.toml files? You could hide the username if you want. 

As of now, my code is:
**_aw-qt.toml_**
`[aw-qt]
#autostart_modules = ["aw-server", "aw-watcher-afk", "aw-watcher-window", "aw-watcher-utilization"]

[aw-qt-testing]
#autostart_modules = ["aw-server", "aw-watcher-afk", "aw-watcher-window"]`

**_aw-server.toml_**
`[server]
#host = "localhost"
#port = "5600"
#storage = "peewee"
#cors_origins = ""

[server.custom_static]
#aw-watcher-utilization = '''C:\Users\<USER>\AppData\Local\activitywatch\activitywatch\aw-watcher-utilization\visualization'''

[server-testing]
#host = "localhost"
#port = "5666"
#storage = "peewee"
#cors_origins = ""

[server-testing.custom_static]`

**Comment by MikeStirner** [comment]
Wait... currently the Installing instructions step 3 still says:
Move the folder to the directly ActivityWatch is installed (depends on your setup). For example, on Windows: C:\Users\<USER>\AppData\Local\activitywatch\activitywatch\aw-watcher-utilization

But should it be?:
<USER>\AppData\Local\Programs\ActivityWatch\aw-watcher-utilization

I can't get it to run automatically. Should I put it in the programs folder location instead?
